<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch6_ex_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part2/ch6/ch6_ex_classification.ipynb)

# Section1

In [ ]:
# 1. 문제 정의
## 평가 지료 : roc-auc
## Target : Outcome (예측할 컬럼 0 : 정상, 1 : 당뇨병)
## 최종파일 : 'result.csv' (컬럼 1개 'pred' 확률값(실수))

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_test.csv")

## 탐색적 데이터 분석 (EDA)
## 데이터 크기 파악
print(train.shape, test.shape)
print("\n") ## 줄바꿈

## 데이터 샘플 확인
print("-------Train 데이터 샘플 -------")
print(train.head(2)) # 컬럼명, 데이터 타입 확인
print("\n\n") ## 줄바꿈
print("-------Test 데이터 샘플 -------")
print(test.head(2)) # 컬럼명, 데이터 타입 확인

## 데이터 자료형 확인
print(train.info(), test.info()) ## 실수 / 정수

### train, test 결측치 수 확인
print(train.isnull().sum(), test.isnull().sum()) ## 둘 다 결측치 X
print("\n\n")

### Target 빈도
print(train['Outcome'].value_counts())

(614, 9) (154, 8)


-------Train 데이터 샘플 -------
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1      118             58             36       94  33.3
1            3      173             78             39      185  33.8

   DiabetesPedigreeFunction  Age  Outcome
0                     0.261   23        0
1                     0.970   31        1



-------Test 데이터 샘플 -------
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            3      102             74              0        0  29.5
1            5      104             74              0        0  28.8

   DiabetesPedigreeFunction  Age
0                     0.121   32
1                     0.153   48
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               614 non-null    int64
 1   Glucose                   614 non-null    int64
 2   BloodPressure             614 non-null    int64
 3   SkinThickness             614 non-null    int64
 4   Insulin                   614 non-null    int64
 5   BMI                       614 non-null    float64
 6   DiabetesPedigreeFunction  614 non-null    float64
 7   Age                       614 non-null    int64
 8   Outcome                   614 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 43.3 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               154 non-null    int64
 1   Glucose                   154 non-null    int64
 2   BloodPressure             154 non-null    int64
 3   SkinThickness             154 non-null    int64
 4   Insulin                   154 non-null    int64
 5   BMI                       154 non-null    float64
 6   DiabetesPedigreeFunction  154 non-null    float64
 7   Age                       154 non-null    int64
dtypes: float64(2), int64(6)
memory usage: 9.8 KB
None None
Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64 Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
dtype: int64



Outcome
0    403
1    211
Name: count, dtype: int64

### 베이스라인

In [ ]:
# 1. 문제정의
# 평가: roc-auc
# target: Outcome
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("diabetes_train.csv")
# test = pd.read_csv("diabetes_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("\n") # 줄 바꿈

print("===== train 데이터 샘플 =====")
print(train.head(1))
print("\n")

print("===== test 데이터 샘플 =====")
print(test.head(1))
print("\n")

print("===== 데이터 정보(자료형) =====")
print(train.info())
print("\n")

print("===== train 결측치 수 =====")
print(train.isnull().sum().sum())
print("\n")

print("===== test 결측치 수 =====")
print(test.isnull().sum().sum())
print("\n")

print("===== target 빈도 =====")
print(train['Outcome'].value_counts())

===== 데이터 크기 =====
Train Shape: (614, 9)
Test Shape: (154, 8)


===== train 데이터 샘플 =====
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1      118             58             36       94  33.3

   DiabetesPedigreeFunction  Age  Outcome
0                     0.261   23        0


===== test 데이터 샘플 =====
   Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            3      102             74              0        0  29.5

   DiabetesPedigreeFunction  Age
0                     0.121   32


===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               614 non-null    int64
 1   Glucose                   614 non-null    int64
 2   BloodPressure             614 non-null    int64
 3   SkinThickness             614 non-null    int64
 4   Insulin                   614 non-null    int64
 5   BMI                       614 non-null    float64
 6   DiabetesPedigreeFunction  614 non-null    float64
 7   Age                       614 non-null    int64
 8   Outcome                   614 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 43.3 KB
None


===== train 결측치 수 =====
0


===== test 결측치 수 =====
0


===== target 빈도 =====
Outcome
0    403
1    211
Name: count, dtype: int64

In [ ]:
## 데이터 전처리
## 수치형 + 결측값 없음 = 전처리 생략
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_test.csv")


## 예측값 분리
target = train.pop('Outcome') ## 한 번만 수행

## 검증 데이터 분할   : 라이브러리 제대로 기억할 것
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

## 분할 데이터 크기 확인
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape) ## 시리즈 형태(num,)로 변환 되었는지 확인

## 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)   ## random_state=0 필수 옵션임ㅠ 까먹지 말자.
rf.fit(X_train, y_train)
pred = rf.predict_proba(X_val)

### 예측 결과 확인
print(pred[:10])
print(rf.classes_)

## 데이터 검증
from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
## roc_auc_socre 확인
print('roc_auc : ', roc_auc)

## 예측 및 결과 파일 생성 (얘가 진짜임)
pred = rf.predict_proba(test)

## 데이터 프레임(submmit) 변환 - 결과 파일 생성
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False) ## to_csv() - 옵션:"파일명", index=False

### 제출 파일 검증
print(pd.read_csv("result.csv").head(5))

## 머리에 안 들어오는 빅분기 실기
### 그냥 손에 계속 익혀야 할 듯..

(491, 8) (123, 8) (491,) (123,)
[[0.88 0.12]
 [0.29 0.71]
 [0.41 0.59]
 [0.75 0.25]
 [0.89 0.11]
 [0.76 0.24]
 [0.49 0.51]
 [0.6  0.4 ]
 [0.48 0.52]
 [0.85 0.15]]
[0 1]
roc_auc :  0.8002739726027398
   pred
0  0.17
1  0.33
2  0.11
3  0.04
4  0.09

In [ ]:
# 4. 데이터 전처리
target = train.pop('Outcome')

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

print("\n ===== 분할된 데이터 크기 =====")
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

print("\n ===== 예측 결과 확인 (샘플 5개) =====")
print(pred[:5])

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('\n roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

# 제출파일 확인
print("\n ===== 제출파일 (샘플 5개) =====")
print(pd.read_csv("result.csv").head())

KeyError: 'Outcome'

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("diabetes_train.csv")
# test = pd.read_csv("diabetes_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/diabetes_test.csv")

# 4. 데이터 전처리
# 스케일링
target = train.pop('Outcome')
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
train = scaler.fit_transform(train)
test = scaler.transform(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, n_estimators=500, random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

# 스케일링: MinMaxScaler 0.8031506849315069 8(StandardScaler, RobustScaler 대입)
# max_depth=5: 0.8153424657534246 (3, 5, 7 대입)
# n_estimators=500: 0.8246575342465753 (200, 400, 500 대입)

# Section2

### 베이스라인

In [29]:
## 1. 문제 정의
## 평가 : roc_auc 평가지료
## 최종 파일 : 'result.csv'
## 예측 컬럼 : 'target' (0: 새 일자리를 찾지 않음 / 1: 새 일자리를 찾음)
## pred: 예측 값(이직할 확률) 컬럼 1개

# 2. 라이브러리 불러오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_test.csv")

# 3. 탐색적 데이터 분석 (데이터 크기 / 데이터 자료형 / 데이터 결측치 / ++여기서는 카테고리별 수도 필요)
# print("-------------- 데이터 크기 train/test --------------\n")
# print(train.shape, test.shape)

# print("-------------- 자료형 train/test --------------\n")
# print(train.info(), test.info())   ## object 10 / int 2 / float 2

## 기초통계량
# print(train.describe())

## 데이터 샘플
# print(train.head(3))
# print("--------- train/test 카테고리별 수-----------\n")
# print(train.nunique(), test.nunique())

# print("--------- train/test 결측치 개수 -----------\n")
# print(train.isnull().sum(), test.isnull().sum()) ### 결측치 다수 존재

# ####### target 빈도 필히 확인..!!!!
# print("----------- target 빈도 수 --------------\n")
# print(train['target'].value_counts())



## 4. 데이터 전처리 - sklearn 아님ㅠ
# from sklearn.preprocessing import

## 결과값('target') 분리
target = train.pop('target')

## 결측치 처리 - 데이터 종류에 따라 결측치 처리 방법 선택
train = train.fillna('X')
test = test.fillna('X')

## 원-핫 인코딩 (trian/test 데이터 합쳐서 진행)
combined = pd.concat([train,test])
# combined = pd.concat([train,test]) ## 데이터 합치기

## 원-핫 인코딩 수행  (get_dummies()는 pd의 내장함수)
combined_dummies = pd.get_dummies(combined)
## train / test 구분  (1. train 데이터 길이 확인 - 데이터 길이로 영역 구분 : 아까 합쳐서 인코딩 했으니까 다시 분리)
n_train = len(train)
train = combined_dummies[:n_train]  ## train = :n_train
test = combined_dummies[n_train:]   ## test == n_train:

# 5. 검증 데이터 나누기  - 여기서 train_test_split 사용 model_selection
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)  ## ('학습 데이터', '대상' : 아까 빼놓은 target, 검증 데이터 분리 비, 고정값)

# 6. 머신러닝 학습 - 여기서 RandomForest 사용
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0) ## RandomForest 사용
rf.fit(X_train, y_train) ## 학습 진행
pred = rf.predict_proba(X_val) ## 예측  rf 가져오기 - rf.fit(학습 Dt) - predict_proba(X_val) 평가

# 7. 평가지표 사용 검증 metrics - roc_auc
from sklearn.metrics import roc_auc_score

roc_auc = roc_auc_score(y_val, pred[:,1])  ### y_val(y_value 값), pred[:,1] 사용
print("roc_auc : ", roc_auc) ### 0.7730...(이하 생략)

## 8. 파일 생성 (데이터 프레임 변환)
pred = rf.predict_proba(test) ## 실제 데이터(test)로 예측 수행
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

## 파일 생성 확인 (검증)
file = pd.read_csv("result.csv")
display(file) ## 확인 완료

roc_auc :  0.7730742036233207

      pred
0     0.23
1     0.50
2     0.61
3     0.07
4     0.02
...    ...
3827  0.13
3828  0.19
3829  0.06
3830  0.13
3831  0.12

[3832 rows x 1 columns]

In [ ]:
# 1. 문제정의
# 평가: roc-auc
# target: target
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("hr_train.csv")
# test = pd.read_csv("hr_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum())

print("\n ===== train/test 카테고리별 수 =====")
print(train.nunique())
print(test.nunique())

print("\n ===== target 빈도 =====")
print(train['target'].value_counts())

In [ ]:
# train = pd.read_csv("hr_train.csv")
# test = pd.read_csv("hr_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_test.csv")
cols = train.select_dtypes(include='object').columns
for col in cols:
    set_train = set(train[col])
    set_test= set(test[col])
    same = (set_train == set_test)
    if same:
        print(col, "\t카테고리 동일함")
    else:
        print(col, "\t카테고리 동일하지 않음")

In [ ]:
# 4. 데이터 전처리
target = train.pop('target')

# 결측치 처리
train = train.fillna("X")
test = test.fillna("X")

# train과 test 합쳐서 원핫인코딩
combined = pd.concat([train, test])
combined_dummies = pd.get_dummies(combined)
n_train = len(train)
train = combined_dummies[:n_train]
test = combined_dummies[n_train:]

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("hr_train.csv")
# test = pd.read_csv("hr_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/hr_test.csv")

# 4. 데이터 전처리
target = train.pop('target')

# 결측치 처리
train = train.fillna("X")
test = test.fillna("X")

# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
combined = pd.concat([train, test])
cols = train.select_dtypes(include='object').columns

for col in cols:
    le = LabelEncoder()
    combined[col] = le.fit_transform(combined[col])

n_train = len(train)
train = combined[:n_train]
test = combined[n_train:]

# id 제거 (성능 떨어짐)
# train = train.drop('enrollee_id', axis=1)
# test = test.drop('enrollee_id', axis=1)

# 스케일링
from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
n_cols = train.select_dtypes(exclude='object').columns
train = scaler.fit_transform(train)
test = scaler.transform(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=7, n_estimators=200, random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict_proba(X_val)

from sklearn.metrics import roc_auc_score
roc_auc = roc_auc_score(y_val, pred[:,1])
print('roc_auc:', roc_auc)

# 7. 예측 및 결과 파일 생성
pred = rf.predict_proba(test)
submit = pd.DataFrame({'pred':pred[:,1]})
submit.to_csv("result.csv", index=False)

# Section3

### 베이스라인

In [65]:
# 1. 문제 정의
## 평가지표 : f1-score 평가지표
## 결과값 : pred - 1개의 예측값 컬럼 포함
## 제출 파일명 : "result.csv"
## 예측 컬럼 : STATUS (0: 채무 이행, 1: 채무 불이행) - 채무 불이행 예측

# 1. 라이브러리 불러오기
import pandas as pd

## 2. 데이터 불러오기
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_test.csv")

# # 3. 탐색적 데이터 분석 (데이터 크기 / 자료형 / 데이터 샘플 / 결측치 수 / target 빈도 수)
# print(train.shape, test.shape)  ## 25519,19 / 7591,18

# print("\n\n----- 자료형 -----\n")
# print(train.info(), test.info()) ## int / float / object

# print("\n\n--------결측치 수----------\n")
# print(train.isnull().sum(), test.isnull().sum()) ## train 데이터에 1 항목 존재

# print("\n\n---------- target 빈도 수 ----------")
# print(train['STATUS'].value_counts())  ### 25085, 434 -> 불균형이 심한 데이터


# ### 여기서는 범주형 데이터 카테고리도 확인
# cols = train.select_dtypes(include='object').columns
# for col in cols:
#   set_train = set(train[col])
#   set_test = set(test[col])
#   same = (set_train==set_test)
#   if same:
#     print(col, "\t카테고리 동일함")
#   else:
#     print(col, "\t카테고리 동일하지 않음")

## 4. 데이터 전처리 수행

# 4-1. 결측치 처리 OCCUPATION 뭐시기 train 데이터에 존재
print("삭제 전 : ", train.shape) ## 삭제 여부를 확인하기 위해 전후 데이터 크기 확인
train.dropna(subset=['OCCUPATION_TYPE'], inplace=True) ## dropna() 함수 사용, subset=['삭제할 컬럼'], inplace=True : 대체한 값으로 저장
print("삭제 후 : ", train.shape) ## (25519, 19) -> (17543, 19) 로 데이터 크기 축소된 것 확인
# print(train.isnull().sum()) ## 결측치 없음 확인

## target 꺼내기 - 행 삭제 시 행 삭제 후 진행
target = train.pop('STATUS')

## 5. 원-핫 인코딩 (train/test 따로 인코딩 수행)
train = pd.get_dummies(train)
test = pd.get_dummies(test)

## 6. 검증 데이터 분할 - model_selection / train_test_split
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0) ## 첫 번째 인자 값 = train (O), X_train (X) 아니 X_train 만드는데 X_train을 왜 넣음

## 7. 데이터 학습
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0) # 값 고정
rf.fit(X_train, y_train) ## train 값들로 학습
### 평가지표가 f1_score 이니까 예측에 predict 씀 (predict_proba 아님)
pred = rf.predict(X_val)  ## predict_prova(예측) 인자값은 X_val 넣는거임 y_val은 평가지료에서 씀

## 8. 평가 - 평가지표 f1_score
from sklearn.metrics import f1_score
## 실제 예측 >> 여기 아님ㅠ (ValueErr)
score = f1_score(y_val, pred)  ## pred 변수를 직접(인덱스 지정 없이) 넣어줌
### ???? ValueError: Found input variables with inconsistent numbers of samples: [3509, 7591]
print("f1_score : ", score)  ## 0.22018...(이하 생략)

## 9. 예측 및 결과 파일 생성
## 실제 예측 >> 여기임
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred}) ## DataFrame({'이름':pred}) 형식 기억 좀
submit.to_csv("result.csv", index=False)

## 파일 검증
file = pd.read_csv("result.csv")
display(file) ### pred 0, 0, 0, 0 ,... 나오는게 맞는거임 -> 검증 완료

삭제 전 :  (25519, 19)
삭제 후 :  (17543, 19)
f1_score :  0.22018348623853212

      pred
0        0
1        0
2        0
3        0
4        0
...    ...
7586     0
7587     0
7588     0
7589     0
7590     0

[7591 rows x 1 columns]

In [63]:
# 1. 문제정의
# 평가: f1
# target: STATUS
# 최종파일: result.csv(컬럼 1개 pred)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("creditcard_train.csv")
# test = pd.read_csv("creditcard_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print(train.shape, test.shape)

print("\n ===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum())

print("\n ===== 범주형 테이터 카테고리 =====")
cols = train.select_dtypes(include='object').columns
for col in cols:
    set_train = set(train[col])
    set_test= set(test[col])
    same = (set_train == set_test)
    if same:
        print(col, "\t카테고리 동일함")
    else:
        print(col, "\t카테고리 동일하지 않음")

print("\n ===== target 빈도 =====")
print(train['STATUS'].value_counts())

===== 데이터 크기 =====
(25519, 19) (7591, 18)

 ===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25519 entries, 0 to 25518
Data columns (total 19 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   25519 non-null  int64
 1   CODE_GENDER          25519 non-null  object
 2   FLAG_OWN_CAR         25519 non-null  object
 3   FLAG_OWN_REALTY      25519 non-null  object
 4   CNT_CHILDREN         25519 non-null  int64
 5   AMT_INCOME_TOTAL     25519 non-null  float64
 6   NAME_INCOME_TYPE     25519 non-null  object
 7   NAME_EDUCATION_TYPE  25519 non-null  object
 8   NAME_FAMILY_STATUS   25519 non-null  object
 9   NAME_HOUSING_TYPE    25519 non-null  object
 10  DAYS_BIRTH           25519 non-null  int64
 11  DAYS_EMPLOYED        25519 non-null  int64
 12  FLAG_MOBIL           25519 non-null  int64
 13  FLAG_WORK_PHONE      25519 non-null  int64
 14  FLAG_PHONE           25519 non-null  int64
 15  FLAG_EMAIL           25519 non-null  int64
 16  OCCUPATION_TYPE      17543 non-null  object
 17  CNT_FAM_MEMBERS      25519 non-null  float64
 18  STATUS               25519 non-null  int64
dtypes: float64(2), int64(9), object(8)
memory usage: 3.7+ MB
None

 ===== train 결측치 수 =====
ID                        0
CODE_GENDER               0
FLAG_OWN_CAR              0
FLAG_OWN_REALTY           0
CNT_CHILDREN              0
AMT_INCOME_TOTAL          0
NAME_INCOME_TYPE          0
NAME_EDUCATION_TYPE       0
NAME_FAMILY_STATUS        0
NAME_HOUSING_TYPE         0
DAYS_BIRTH                0
DAYS_EMPLOYED             0
FLAG_MOBIL                0
FLAG_WORK_PHONE           0
FLAG_PHONE                0
FLAG_EMAIL                0
OCCUPATION_TYPE        7976
CNT_FAM_MEMBERS           0
STATUS                    0
dtype: int64

 ===== test 결측치 수 =====
ID                     0
CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
DAYS_BIRTH             0
DAYS_EMPLOYED          0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
dtype: int64

 ===== 범주형 테이터 카테고리 =====
CODE_GENDER 	카테고리 동일함
FLAG_OWN_CAR 	카테고리 동일함
FLAG_OWN_REALTY 	카테고리 동일함
NAME_INCOME_TYPE 	카테고리 동일함
NAME_EDUCATION_TYPE 	카테고리 동일함
NAME_FAMILY_STATUS 	카테고리 동일함
NAME_HOUSING_TYPE 	카테고리 동일함
OCCUPATION_TYPE 	카테고리 동일하지 않음

 ===== target 빈도 =====
STATUS
0    25085
1      434
Name: count, dtype: int64

In [64]:
# 4. 데이터 전처리
# 결측치 처리
print("삭제 전:",train.shape)
train.dropna(subset=['OCCUPATION_TYPE'], inplace=True)
print("삭제 후:",train.shape)

target = train.pop('STATUS')

# 원핫인코딩
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
score = f1_score(y_val, pred)
print('\n f1:', score)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)


## 파일 검증
file = pd.read_csv("result.csv")
display(file)

삭제 전: (25519, 19)
삭제 후: (17543, 19)

 f1: 0.22018348623853212

      pred
0        0
1        0
2        0
3        0
4        0
...    ...
7586     0
7587     0
7588     0
7589     0
7590     0

[7591 rows x 1 columns]

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("creditcard_train.csv")
# test = pd.read_csv("creditcard_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch6/creditcard_test.csv")

# 4. 데이터 전처리
# 결측치 처리 (최빈값)
freq = train['OCCUPATION_TYPE'].mode()[0]
train['OCCUPATION_TYPE'] = train['OCCUPATION_TYPE'].fillna(freq)
test['OCCUPATION_TYPE'] = test['OCCUPATION_TYPE'].fillna(freq)

target = train.pop('STATUS')

# 스케일링 (성능 개선 효과 없음)
# from sklearn.preprocessing import RobustScaler
# scaler = RobustScaler()
# n_cols = train.select_dtypes(exclude='object').columns[:-1] # STATUS를 제외한 int, float
# train[n_cols] = scaler.fit_transform(train[n_cols])
# test[n_cols] = scaler.transform(test[n_cols])

# ID 제외
train = train.drop('ID', axis=1)
test = test.drop('ID', axis=1)

# 레이블 인코딩
from sklearn.preprocessing import LabelEncoder
cols = train.select_dtypes(include='object').columns
for col in cols:
    le = LabelEncoder()
    train[col] = le.fit_transform(train[col])
    test[col] = le.transform(test[col])

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=200, class_weight='balanced', random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
score = f1_score(y_val, pred)
print('f1:', score)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)