<a href="https://colab.research.google.com/github/ecuirty-kr/1_DataAnalysis/blob/main/ch7_ex_multi_class_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[구글 코랩(Colab)에서 실행하기](https://colab.research.google.com/github/lovedlim/bigdata_analyst_cert_v2/blob/main/part2/ch7/ch7_ex_multi_class_classification.ipynb)

# Section1

### 베이스라인

In [17]:
# 1. 문제 정의
## 평가 지표: f1-macro
## 예측 컬럼 : Credit_Score(Good, Standard, Poor) 세 가지 값으로 예측
## 제출 파일명 : "result.csv" (pred : 예측값 컬럼 1개)

# 2. 라이브러리 불러오기 + 데이터 가져오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_test.csv")

# 3. 탐색적 데이터 분석 (EDA) - 데이터 크기, 자료형, 데이터 샘플(생략), 결측치, target 빈도 수
# print("\n\n------- 데이터 크기 -----------")
# print(train.shape, test.shape) ## (4198, 21) (1499, 20)

# print("\n\n------- 데이터 자료형 -----------")
# print(train.info(), test.info())  ## float 16 / object 4(train은 4개 / test는 3개 - Credit_Score 컬럼 없음)

# print("\n\n------- 데이터 결측치 -----------")
# print(train.isnull().sum(), test.isnull().sum())  ## 결측치 없음

# print("\n\n------- Target 빈도 수 -----------")
# print(train['Credit_Score'].value_counts()) ## Standard  2225 / Poor 1232 / Good  741

# 4. 데이터 전처리
## 원-핫 인코딩 시 target 컬럼 제외 (자료형이 object 형이라 컬럼이 다수 개 생성됨)
target = train.pop('Credit_Score')
train = pd.get_dummies(train)
test = pd.get_dummies(test)

## 5. 검증 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0) ## 오 여기까지 수월

## + 분할된 데이터 크기 확인
print(X_train.shape, X_val.shape, y_train.shape, y_val.shape)  ## y_tr, y_val 값이 시리즈 형태(값, )로 존재하는지 확인

## 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)  ## 랜덤 포레스트 사용 (random=0 고정값)
rf.fit(X_train, y_train) ## 학습
pred = rf.predict(X_val) ## 예측 X_val : f1_score 평가지표 사용하므로 predict()

## 평가 지표 f1_score
from sklearn.metrics import f1_score
score = f1_score(y_val, pred, average='macro') ## f1-macro 평가지표 사용 시 옵션 값 average='macro' 추가
print("f1-macro  : ", score) ## f1-macro 평가 값 확인 0.70045...(이하 생략)

## 7. 예측 및 결과 파일 생성
pred = rf.predict(test) ## 실제 데이터로 예측 수행
submit = pd.DataFrame({'pred':pred}) ## 데이터 프레임 생성
submit.to_csv("result.csv", index=False) ## 제출 파일 생성

## 결과 파일 검증
file = pd.read_csv("result.csv")
display(file) ## 검증 완료

(3358, 29) (840, 29) (3358,) (840,)
f1-macro  :  0.7004593488873695

          pred
0         Poor
1         Good
2     Standard
3         Good
4     Standard
...        ...
1494  Standard
1495      Poor
1496  Standard
1497      Good
1498  Standard

[1499 rows x 1 columns]

In [ ]:
# 1. 문제정의
# 평가: f1 macro
# target: Credit_Score
# 최종파일: result.csv(컬럼 1개 pred)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("score_train.csv")
# test = pd.read_csv("score_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print("Train Shape:", train.shape)
print("Test Shape:", test.shape)
print("\n") # 줄 바꿈

print("===== 데이터 정보(자료형) =====")
print(train.info())
print("\n")

print("===== train 결측치 수 =====")
print(train.isnull().sum().sum())
print("\n")

print("===== test 결측치 수 =====")
print(test.isnull().sum().sum())
print("\n")

print("===== target 빈도 =====")
print(train['Credit_Score'].value_counts())

===== 데이터 크기 =====
Train Shape: (4198, 21)
Test Shape: (1499, 20)


===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4198 entries, 0 to 4197
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Delay_from_due_date       4198 non-null   float64
 1   Num_of_Delayed_Payment    4198 non-null   float64
 2   Num_Credit_Inquiries      4198 non-null   float64
 3   Credit_Utilization_Ratio  4198 non-null   float64
 4   Credit_History_Age        4198 non-null   float64
 5   Payment_of_Min_Amount     4198 non-null   object
 6   Amount_invested_monthly   4198 non-null   float64
 7   Monthly_Balance           4198 non-null   float64
 8   Credit_Mix                4198 non-null   object
 9   Payment_Behaviour         4198 non-null   object
 10  Age                       4198 non-null   float64
 11  Annual_Income             4198 non-null   float64
 12  Num_Bank_Accounts         4198 non-null   float64
 13  Num_Credit_Card           4198 non-null   float64
 14  Interest_Rate             4198 non-null   float64
 15  Num_of_Loan               4198 non-null   float64
 16  Monthly_Inhand_Salary     4198 non-null   float64
 17  Changed_Credit_Limit      4198 non-null   float64
 18  Outstanding_Debt          4198 non-null   float64
 19  Total_EMI_per_month       4198 non-null   float64
 20  Credit_Score              4198 non-null   object
dtypes: float64(17), object(4)
memory usage: 688.9+ KB
None


===== train 결측치 수 =====
0


===== test 결측치 수 =====
0


===== target 빈도 =====
Credit_Score
Standard    2225
Poor        1232
Good         741
Name: count, dtype: int64

In [ ]:
# 4. 데이터 전처리
# 원핫인코딩 (target컬럼이 object형이라 제외)
target = train.pop('Credit_Score')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

print("\n ===== 분할된 데이터 크기 =====")
print(X_tr.shape, X_val.shape, y_tr.shape, y_val.shape)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

# 제출파일 확인
print("\n ===== 제출파일 (샘플 5개) =====")
print(pd.read_csv("result.csv").head())

 ===== 분할된 데이터 크기 =====
(3358, 29) (840, 29) (3358,) (840,)

 f1-macro: 0.7004593488873695

 ===== 제출파일 (샘플 5개) =====
       pred
0      Poor
1      Good
2  Standard
3      Good
4  Standard

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

# train = pd.read_csv("score_train.csv")
# test = pd.read_csv("score_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/score_test.csv")

# 4. 데이터 전처리
target = train.pop('Credit_Score')

# 스케일링
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
cols = train.select_dtypes(include=['int', 'float']).columns
train[cols] = scaler.fit_transform(train[cols])
test[cols] = scaler.transform(test[cols])

# 원핫인코딩
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 레이블 인코딩
# target = train.pop('Credit_Score')
# from sklearn.preprocessing import LabelEncoder
# cols = train.select_dtypes(include='object').columns
# for col in cols:
#     le = LabelEncoder()
#     train[col] = le.fit_transform(train[col])
#     test[col] = le.transform(test[col])

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('f1-macro:', f1)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

f1-macro: 0.7020460066061172

# Section2

### 베이스라인

In [32]:
## 약물 종류 예측
# 1. 문제 정의
## 예측 컬럼 : Drug (DrugY, drugX, drugA, drugC, drugB) : 다중 분류
## 제출 파일 "result.csv"
## 평가 지표 : f1-macro
## pred : 예측 값 1 개 컬럼 포함

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_test.csv")

## 3. 탐색적 데이터 분석(EDA) : 데이터 크기 / 데이터 자료형 / 결측치 수 / target 빈도 수
# print("\n\n------------- 데이터 크기 ---------------\n")
# print(train.shape, test.shape) ## (100, 6) (100, 5)

# print("\n\n------------- 데이터 자료형 ---------------\n")
# print(train.info(), test.info())  ## object 3 / int 1 / float 1 (train 데이터 object 1개 더 존재 'Drug' (4개))

# print("\n\n------------- 데이터 결측치 수 ---------------\n")
# print(train.isnull().sum(), test.isnull().sum()) ## 결측치 없음 -  dropna(replace=Trua) 사용 X

# print("\n\n------------- target 빈도 수 ---------------\n")
# print(train['Drug'].value_counts()) ## 41, 34, 13, 8, 4
## 카테고리별 수 > 일단은 확인 생략
## 어깨 말려드는 중.. 결린다

## 4. 데이터 전처리
# 원-핫 인코딩
target = train.pop('Drug')
train = pd.get_dummies(train)
test = pd.get_dummies(test)

## 5. 검증 데이터 분리
from sklearn.model_selection import train_test_split

X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0) ##  test_size=0.2 는 전체 데이터의 20%를 검증 데이터로 사용한다는 의미임!

## 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)
rf.fit(X_train,y_train)
pred = rf.predict(X_val) ## f1-macro 평가지표 사용할 예정이므로 predict() 함수 사용

## 평가지표 : f1-macro
from sklearn.metrics import f1_score

score = f1_score(y_val, pred, average='macro') ### 이전 문제와 마찬가지로 f1-macro 이므로 옵션에 average='macro' 추가
print("f1-macro : ", score) ## f1-score 값 확인 : 1.0
### f1-macro score 값이 1이 나오는 것은 문제있는 것 >> 거의 만점에 가까운..

## 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

## 결과 파일 검증
file = pd.read_csv("result.csv")
display(file)  ## 확인 완료

## 1.0 결과를 보다 정밀하게 검증하려면 Cross-Validation 사용을 권장하나, 현재는 스킵-

f1-macro :  1.0

     pred
0   DrugY
1   DrugY
2   DrugY
3   DrugY
4   drugB
..    ...
95  drugX
96  drugC
97  DrugY
98  DrugY
99  drugX

[100 rows x 1 columns]

In [ ]:
# 1. 문제정의
# 평가: f1-macro
# target: Drug
# 최종파일: result.csv(컬럼 1개 pred, 1확률값)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
# train = pd.read_csv("drug_train.csv")
# test = pd.read_csv("drug_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum().sum())

print("\n ===== train/test 카테고리별 수 =====")
print(train[['Sex', 'BP', 'Cholesterol']].nunique())
print(test[['Sex', 'BP', 'Cholesterol']].nunique())

print("\n ===== target 빈도 =====")
print(train['Drug'].value_counts())

===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Age          100 non-null    int64
 1   Sex          100 non-null    object
 2   BP           100 non-null    object
 3   Cholesterol  100 non-null    object
 4   Na_to_K      100 non-null    float64
 5   Drug         100 non-null    object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.8+ KB
None

 ===== train 결측치 수 =====
0

 ===== test 결측치 수 =====
0

 ===== train/test 카테고리별 수 =====
Sex            2
BP             3
Cholesterol    2
dtype: int64
Sex            2
BP             3
Cholesterol    2
dtype: int64

 ===== target 빈도 =====
Drug
DrugY    41
drugX    34
drugA    13
drugB     8
drugC     4
Name: count, dtype: int64

In [ ]:
# 4. 데이터 전처리
# 원핫인코딩
target = train.pop('Drug')
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
f1 = f1_score(y_val, pred, average='macro')
print('\n f1-macro:', f1)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

 f1-macro: 1.0

In [ ]:
# 크로스 밸리데이션(cross-validation)
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
f1_scores = cross_val_score(rf, train, target, cv=3, scoring='f1_macro')
print(f1_scores)
print(f1_scores.mean())

[1.         0.93777778 0.78461538]
0.9074643874643874

In [ ]:
# scoring에 입력 가능한 평가지표 확인 방법
from sklearn.metrics import get_scorer_names
print(get_scorer_names())

['accuracy', 'adjusted_mutual_info_score', 'adjusted_rand_score', 'average_precision', 'balanced_accuracy', 'completeness_score', 'd2_absolute_error_score', 'explained_variance', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'fowlkes_mallows_score', 'homogeneity_score', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted', 'matthews_corrcoef', 'mutual_info_score', 'neg_brier_score', 'neg_log_loss', 'neg_max_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_gamma_deviance', 'neg_mean_poisson_deviance', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_median_absolute_error', 'neg_negative_likelihood_ratio', 'neg_root_mean_squared_error', 'neg_root_mean_squared_log_error', 'normalized_mutual_info_score', 'positive_likelihood_ratio', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'r2', 'rand_score', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'roc_auc', 'roc_auc_ovo', 'roc_auc_ovo_weighted', 'roc_auc_ovr', 'roc_auc_ovr_weighted', 'top_k_accuracy', 'v_measure_score']

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
# train = pd.read_csv("drug_train.csv")
# test = pd.read_csv("drug_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/drug_test.csv")

# 4. 데이터 전처리
target = train.pop('Drug')

# 스케일링
# from sklearn.preprocessing import MinMaxScaler
# scaler = MinMaxScaler()
# train['Age'] = scaler.fit_transform(train[['Age']])
# test['Age'] = scaler.transform(test[['Age']])

# 원핫인코딩 (Drug 컬럼 제외)
train = pd.get_dummies(train)
test = pd.get_dummies(test)

# 레이블 인코딩 (Drug 컬럼 제외)
# target = train.pop('Drug')
# from sklearn.preprocessing import LabelEncoder
# cols = train.select_dtypes(include='object').columns
# for col in cols:
#     le = LabelEncoder()
#     train[col] = le.fit_transform(train[col])
#     test[col] = le.transform(test[col])

# 5. 크로스 밸리데이션(cross-validation)
from sklearn.metrics import f1_score
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(random_state=0)
f1_scores = cross_val_score(rf, train, target, cv=3, scoring='f1_macro')
print(f1_scores.mean())

# 6. 머신러닝 학습 및 평가
rf.fit(train, target)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

0.9074643874643874

# Section3

### 베이스라인

In [51]:
## 유리 종류 예측
# 1. 문제 정의
## 예측 컬럼(target) : Type (1, 2, 3, 5, 6, 7)
## pred : 예측값 1개 컬럼 포함
## 평가 지표 : f1-weighted (New!!)
## 제출 파일 : "result.csv"

## 2. 라이브러리 및 데이터 불러오기
import pandas as pd

train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_test.csv")

## 3. 탐색적 데이터 분석 (데이터 크기 / 자료형 / 결측치 수 / target 빈도 수)
# print("\n\n------ 데이터 크기 -------- \n")
# print(train.shape, test.shape) ## (149, 10) (65, 9)

# print("\n\n------ 데이터 자료형 -------- \n")
# print(train.info(), test.info()) ## float 8 (train 데이터에 int 1개 추가 : 'Type' ) >> 전체 수치형 데이터

# print("\n\n------ 데이터 결측치 수 -------- \n")
# print(train.isnull().sum(), test.isnull().sum()) ## 결측치 없음

# print("\n\n------ target 빈도 수  -------- \n")
# print(train['Type'].value_counts()) ##  53,  49,  23,  9,  8,  7 (6가지)

### 데이터 샘플 확인 추가
# print(train.head(2))

## 3. 데이터 전처리 수행
# 원-핫 인코딩
target = train.pop('Type')

train = pd.get_dummies(train)
test = pd.get_dummies(test)

## 4. 검증 데이터 분리
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

## 5. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_train, y_train)
pred = rf.predict(X_val)

# 평가지표 : f1-weighted
from sklearn.metrics import f1_score
score = f1_score(y_val, pred, average='weighted') ## average='weighted' 넣으면 되는지 한 번 해보기 > 된다
print("f1-weighted : ", score)

## 6. 예측 수행 및 결과 파일 생성
pred = rf.predict(test) ## 실제 test 데이터로 예측 수행
submit = pd.DataFrame({'pred':pred}) # pred 데이터 프레임 생성
submit.to_csv("result.csv", index=False) # 기존 인덱스 없이 결과 파일 생성

## 결과 파일 검증
file = pd.read_csv("result.csv")
display(file) ## 검증 완료

f1-weighted :  0.6119801766860591

    pred
0      1
1      2
2      2
3      2
4      2
..   ...
60     1
61     1
62     2
63     1
64     1

[65 rows x 1 columns]

In [49]:
# 1. 문제정의
# 평가: f1-weighted
# target: Type
# 최종파일: result.csv(컬럼 1개 pred)

# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
# train = pd.read_csv("glass_train.csv")
# test = pd.read_csv("glass_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_test.csv")

# 3. 탐색적 데이터 분석(EDA)
print("===== 데이터 크기 =====")
print(train.shape, test.shape)

print("\n ===== train 데이터 샘플 =====")
print(train.head(1))

print("\n ===== test 데이터 샘플 =====")
print(test.head(1))

print("\n ===== 데이터 정보(자료형) =====")
print(train.info())

print("\n ===== train 결측치 수 =====")
print(train.isnull().sum().sum())

print("\n ===== test 결측치 수 =====")
print(test.isnull().sum().sum())

print("\n ===== target 빈도 =====")
print(train['Type'].value_counts())

===== 데이터 크기 =====
(149, 10) (65, 9)

 ===== train 데이터 샘플 =====
        RI     Na    Mg    Al     Si    K    Ca   Ba   Fe  Type
0  1.51829  14.46  2.24  1.62  72.38  0.0  9.26  0.0  0.0     6

 ===== test 데이터 샘플 =====
        RI     Na    Mg    Al     Si     K    Ca   Ba    Fe
0  1.51748  12.86  3.56  1.27  73.21  0.54  8.38  0.0  0.17

 ===== 데이터 정보(자료형) =====
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149 entries, 0 to 148
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   RI      149 non-null    float64
 1   Na      149 non-null    float64
 2   Mg      149 non-null    float64
 3   Al      149 non-null    float64
 4   Si      149 non-null    float64
 5   K       149 non-null    float64
 6   Ca      149 non-null    float64
 7   Ba      149 non-null    float64
 8   Fe      149 non-null    float64
 9   Type    149 non-null    int64
dtypes: float64(9), int64(1)
memory usage: 11.8 KB
None

 ===== train 결측치 수 =====
0

 ===== test 결측치 수 =====
0

 ===== target 빈도 =====
Type
2    53
1    49
7    23
3     9
5     8
6     7
Name: count, dtype: int64

In [50]:
# 4. 데이터 전처리
target = train.pop('Type')

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
score = f1_score(y_val, pred, average='weighted')
print('f1:', score)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

file = pd.read_csv("result.csv")
display(file)

f1: 0.6119801766860591

    pred
0      1
1      2
2      2
3      2
4      2
..   ...
60     1
61     1
62     2
63     1
64     1

[65 rows x 1 columns]

### 성능개선

In [ ]:
# 2. 라이브러리 및 데이터 불러오기
import pandas as pd
# train = pd.read_csv("glass_train.csv")
# test = pd.read_csv("glass_test.csv")
train = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_train.csv")
test = pd.read_csv("https://raw.githubusercontent.com/lovedlim/bigdata_analyst_cert/main/part2/ch7/glass_test.csv")

# 4. 데이터 전처리
target = train.pop('Type')

# 스케일링 효과 없음

# 5. 검증 데이터 분할
from sklearn.model_selection import train_test_split
X_tr, X_val, y_tr, y_val = train_test_split(train, target, test_size=0.2, random_state=0)

# 6. 머신러닝 학습 및 평가
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=5, n_estimators=200, random_state=0)
rf.fit(X_tr, y_tr)
pred = rf.predict(X_val)

from sklearn.metrics import f1_score
score = f1_score(y_val, pred, average='weighted')
print('f1:', score)

# 7. 예측 및 결과 파일 생성
pred = rf.predict(test)
submit = pd.DataFrame({'pred':pred})
submit.to_csv("result.csv", index=False)

f1: 0.6507936507936507